config/routes.rb
Rails.application.routes.draw do

  get 'users/index'
  get 'users/destroy'
# Home page route for shop index pages
root "shop#index"

#categories index and show pages get routes
get 'categories/index'
get 'categories/:id', to: "categories#show", as: "categories_show"

#  get root set oustide of the resource and before it so that rails finds it first
get "shop/index", to:"shop#index"
get "shop-owners/complete", to:"shop_owners#success"
get "shop-owners/cancel", to: "shop_owners#cancel"

# overiding the devise registration controller path to set my own after registration route
# shop routes nested within user and item routes nested within shop
devise_for :users, controllers: { registrations: "registrations" }
resources :users do
    get "cart", to: "carts#show"
    get "shop-owners", to: "shop_owners#new"
    resources :shop do
      resources :items 
    end
end

delete "users/:user_id/cart/:cart_id/cart_items/:id", to: "cart_items#destroy", as: "user_cart_items"
post "users/:user_id/cart/:cart_id/cart_items", to: "cart_items#create", as: "cart_items"
patch "users/:user_id/cart/:cart_id/cart_items/:id/", to: "cart_items#update", as: "cart_item"

# User profile resource routes
resources :user_profiles

end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :user
  has_many :items, dependent: :destroy
  has_one_attached :shop_image
  validates :name, presence: true, length: { in: 3..20 }
  validates :hook, presence: true, length: { in: 3..45 }

  def self.search(search)
    if search
      find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end

end

app/controllers/shop_controller.rb
class ShopController < ApplicationController

  before_action :authenticate_user!
  before_action :authorise
  skip_before_action :authenticate_user!, only: [:index]
  skip_before_action :authorise, only: [:index, :show, :new]

  def index
      @shop = Shop.where('name LIKE ?', "%#{params[:search]}%")
  end
  
  def show
    @shop = Shop.find(params[:id])
    @cart_item = CartItem.new 
  end
  
  def new
    @shop = current_user.build_shop
  end

  def create
    @shop_new = current_user.create_shop(shop_params)
    current_user.shop.shop_image.attach(shop_params[:shop_image])
    if @shop_new.save
      redirect_to user_shop_path(current_user, @shop_new)
    else
      flash[:error] = @shop_new.errors.full_messages.to_sentence 
    end
  end

  def edit
    @shop = current_user.shop
  end

  def update
    @shop = current_user.shop.update(shop_params)
    if shop_params[:shop_image]
      current_user.shop.shop_image.attach(shop_params[:shop_image])
    end
    redirect_to user_shop_path(current_user)
  end

  def destroy
    @shop = Shop.find(params[:id])
    @shop.destroy
    if ! current_user.has_role?(:admin)
    flash[:alert] = "Your shop was deleted"
    redirect_to user_profile_path(current_user.id)
    else 
      flash[:alert] = "Shop successfully deleted"
      redirect_to user_profile_path(current_user)
    end
  end

  private

  def shop_params
    params.require(:shop).permit(:name, :content, :hook, :shop_image)
  end

  def authorise
  
    return if current_user.has_role?(:admin) || (current_user.id == params[:user_id].to_i)

    flash[:alert] = "soz....You can only create and edit your own shops :("
    
    redirect_to user_profile_path(current_user.id)
  
  end

end

app/helpers/shop_helper.rb
module ShopHelper
end

app/views/shop/_item_card.html.erb
<% shop.items.each do |item| %>
<div class="all-cards" id="item-card">
    <h1><%= item.name %></h1>

    <% if item.item_picture.attached? %>
      <%= image_tag (item.item_picture), id: "item-picture" %>
    <% else %>
      <div id="shop-image-placeholder" ><H1>Placeholder</H1></div>
    <% end %>

    <p style="margin-bottom:0;">Price<br>
      $<%= sprintf '%.2f', item.price %></p>
    <p><%= item.hook %></p>
     
    <%= link_to "view item", user_shop_item_path( item.shop.user, item.shop.id, item.id), style:"color:blue;" "padding-bottom:30px;" %>
    
    <% if current_user.shop %>
    <% if item.shop.id == current_user.shop.id && current_page?(user_shop_item_path(current_user, current_user.shop, params[:id])) %>
    <%= link_to "edit item", edit_user_shop_item_path( item.shop.user, item.shop.id, item.id), style: "font-size:3rem;" "color:blue;" "padding-bottom:30px;" %>
    <% end %> 
    <% end %> 

    <%= form_with model: cart_item, local: true, url: cart_items_path(current_user, current_user.cart.id) do |f| %>
    <%= f.hidden_field :item_id, value: item.id %>
    <%= f.number_field(:quantity, in: 1..10, step: 1, value: 1)%>
    <%= f.submit "Cart +", class: "head-button" %> <br> 
    <% end %>
  
  
  </div>
<% end %>

app/views/shop/_new_form.html.erb
<!-- for wrapper div for styling -->
<div id="edit-form-card" class="all-cards">

        <!-- initialising the rails form helper to render the html form -->
        <%= form_with model: shop, url: path, method: verb, local: true do |shop_form| %>
        
        <div class="form-field">
            <!-- The name field label and text input field -->
            <%= shop_form.label :name, "Shop name" %><br>
            <%= shop_form.text_field :name %>
        </div>

        <div class="form-field">
            <!-- The content field label and text area input -->
            <%= shop_form.label :hook, "A quik hook to appeal to sellers!" %><br>
            <%= shop_form.text_area :hook %>
            </div>
        
        <div class="form-field">
            <!-- The content field label and text area input -->
            <%= shop_form.label :content, "Shop profile content" %><br>
            <%= shop_form.text_area :content%>
        </div>
      
        <div class="form-field">
          <!-- file attachment field for uploading the shop image. :shop_image is
          referenced as attached in the model -->
          <%= shop_form.label :shop_image, "Shop Image Uplaod" %><br>
          <%= shop_form.file_field :shop_image, id: "file-upload" %>
        </div>
        
        <div class="form-field">
          <!-- The form submit button -->
          <%= shop_form.submit "GO!", class: "head-button" %>
        </div>
      
        <% end %>
      
      </div>

app/views/shop/_search_form.html.erb
<!-- Search form -->
<div class="all-cards" id="search-div">
        
        <%= form_tag shop_index_path, method: "get", id: "search-form" do %>
          <div  class="form-field" id="search-field-div">
            <%= text_field_tag :search, params[:search] %>
          </div>
          <div id="search-button-wrap">
            <%= submit_tag 'Search', name: nil, class: "head-button" %>
          </div>
        <% end %>
    
    </div>

app/views/shop/_shop_card.html.erb
<div class="all-cards" id="shop-card">
        <div id="heading-view">
            <h1><%= shop.name %></h1>
            <% unless current_page? user_shop_path(users_id, shop.id) %>
            <%= link_to "View", user_shop_path(users_id, shop.id) %> 
            <% end %>
            <% if current_user && current_user.shop %>
            <% if (current_page? user_shop_path(users_id, shop.id)) && (current_user.shop.id == shop.id) %>
            <%= link_to "Add an Item", new_user_shop_item_path(current_user, current_user.shop.id) %>
            <% end %>
            <% end %>
        </div>
        <% if shop.shop_image.attached? %>
        <%= image_tag (shop.shop_image), width:900, height: 400, id: "shop-picture" %>
        <% else %>
        <div id="shop-image-placeholder" ><H1>Placeholder</H1></div>
        <% end %>
        <div id="shop-hook">
            <%= shop.hook %>
        </div>
        
    </div>

app/views/shop/destroy.html.erb
<h1>Shop#destroy</h1>
<p>Find me in app/views/shop/destroy.html.erb</p>

app/views/shop/edit.html.erb
<div class="all-cards" id="edit-heading"><h1>Edit profile</h1></div>
<%= render "new_form", shop: @shop, verb: "patch", path: user_shop_path %>

app/views/shop/index.html.erb
 <!-- Rendering the seach form -->
<div class="all-cards" id="search-heading">
    <h1>Search Shop Name</h1>
</div>
<%= render "search_form" %>   
    
    <!-- The category browse card -->
    <div class="all-cards" id="category-card">
        <h1 id="profile-form-heading">Categories</h1>
        <%= link_to "Browse", categories_index_path, class: "head-button", id: "category-button" %>
    </div>

<!-- All the things welcome card -->
<div class="all-cards" id="welcome-card">
        <h1>About Us!</h1>
        <p>Welcome to all the things. If you want to buy all the things or maybe sell all the things 
            you have come to the right place !!! Enjoy your visit and happy shopping !!
        </p>
    </div>

<!-- rendering the shop cards passed from controller based on seach parameters if nill or false returns all -->
<% @shop.each do |shop| %>
<%= render "shop_card", shop: shop, users_id: shop.user.id %>
<% end %>

app/views/shop/new.html.erb
<!-- Rendering a heading for the form styled the same as the previous form headings --> 
<!-- Using the same card for most things as is shown below here  -->

<div class="all-cards" id="profile-form-heading-card">
    <h1 id="profile-form-heading">Create Your Shop</h1>
</div>
<%= render "new_form", shop: @shop, path: user_shop_index_path, verb: "post" %>

app/views/shop/show.html.erb
<!-- rendering shop card from the partial shop_card -->
<%= render "shop_card", shop: @shop, users_id: @shop.user %>

<!-- Shop content -->
<div class="all-cards" id="shop-content-card">
    <div id="shop-content-head">
      <h1>About</h1>
        <p id="shop-content"><%= @shop.content %></p>
        <% if params[:user_id].to_i == current_user.id %>
          <%= link_to "edit", edit_user_shop_path(current_user), id: "edit-link" %>
        <% end %>
    </div>
</div>

<%= render "item_card", shop: @shop, cart_item: @cart_item  %>

<% if User.admin_check(current_user) %>
  <div class="all-cards" id="profile-links">
    <%= link_to "Admin delete shop", user_shop_path(@shop.user.id, @shop.id), method: "delete", style: "color:red;"  %>
  </div>
<% end %>