config/routes.rb
Rails.application.routes.draw do

  get 'users/index'
  get 'users/destroy'
# Home page route for shop index pages
root "shop#index"

#categories index and show pages get routes
get 'categories/index'
get 'categories/:id', to: "categories#show", as: "categories_show"

#  get root set oustide of the resource and before it so that rails finds it first
get "shop/index", to:"shop#index"
get "shop-owners/complete", to:"shop_owners#success"
get "shop-owners/cancel", to: "shop_owners#cancel"

# overiding the devise registration controller path to set my own after registration route
# shop routes nested within user and item routes nested within shop
devise_for :users, controllers: { registrations: "registrations" }
resources :users do
    get "cart", to: "carts#show"
    get "shop-owners", to: "shop_owners#new"
    resources :shop do
      resources :items 
    end
end

delete "users/:user_id/cart/:cart_id/cart_items/:id", to: "cart_items#destroy", as: "user_cart_items"
post "users/:user_id/cart/:cart_id/cart_items", to: "cart_items#create", as: "cart_items"
patch "users/:user_id/cart/:cart_id/cart_items/:id/", to: "cart_items#update", as: "cart_item"

# User profile resource routes
resources :user_profiles

end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  belongs_to :user
  has_one_attached :profile_image
end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController

  before_action :authenticate_user!
  before_action :authorise

  def show
    @model = current_user.user_profile
  end

  def edit
    @user_profile = current_user.user_profile
  end

  # fix me!!
  def update
    @user_profile = current_user.user_profile.update(profile_params)
    if profile_params[:profile_image]
    @user_profile = current_user.user_profile.profile_image.attach(profile_params[:profile_image])
    end
    redirect_to user_profile_path(current_user)
  end

  def destroy
  end

  private 
  
  def profile_params
  params.require(:user_profile).permit(:name, :content, :profile_image)
  end

  def authorise
  
    return if current_user.id == params[:id].to_i || User.admin_check(current_user)

    flash[:alert] = "soz...you are only authorised to view/edit your own dasboard :("
    
    redirect_to user_profile_path(current_user.id)
  
  end

  
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/views/user_profiles/_form.html.erb
<!-- for wrapper div for styling -->
<div id="edit-form-card" class="all-cards">

        <!-- initialising the rails form helper to render the html form -->
        <%= form_with model: user_profile, method: "patch", local: true do |edit_user| %>
        
        <div class="form-field">
        <!-- The name field label and text input field -->
        <%= edit_user.label :name, "Username" %><br>
        <%= edit_user.text_field :name %>
        </div>
        
        <div class="form-field">
        <!-- The content field label and text area input -->
        <%= edit_user.label :content, "A few sentences about yourself !!" %><br>
        <%= edit_user.text_area :content%>
        </div>
      
        <div class="form-field">
        <!-- file attachment field for uploading the profile image. :profile_image is
        referenced as attached in the model -->
        <%= edit_user.file_field :profile_image, id: "file-upload" %>
        </div>
        
        <div class="form-field">
          <!-- The form submit button -->
          <%= edit_user.submit "Edit", class: "head-button" %>
        </div>
      
        <% end %>
      
      </div>

app/views/user_profiles/_profile_card.html.erb
<div class="all-cards" id="profile-card">

        <!-- Setting the dshboard heading to the current user -->
        <h1 id="profile-heading">Your Dashboard <%= current_user.user_profile.name %>!</h1>
        
        <!-- Profile image and content rendered here -->

        <div id="profile-wrap">
            <% if model.profile_image.attached? %>
              <%= image_tag model.profile_image, style: "width: 180px; height:200px;", id: "profile-image" %>
            <% else %>
              <div id="user-image"><p>Placeholder</p></div>
            <% end %>

        <div id="profile-content"><p><%= current_user.user_profile.content %></p></div>
        </div>
         <!-- links to the edit form for the user profile -->
        <%= link_to "Edit", edit_user_profile_path(current_user) %>
    
    </div>

app/views/user_profiles/edit.html.erb
<div class="all-cards" id="profile-form-heading-card">
  <h1 id="profile-form-heading">Edit Your Profile</h1>
</div>
<%= render "form", user_profile: @user_profile %>

app/views/user_profiles/show.html.erb
<!-- rendering the profile card and passing in the user profile model -->
<%= render "profile_card", model: @model %>

<!-- Links card probly to small to warrant a partial -->
<div class="all-cards" id="profile-links">
  <%= link_to "Go Shopping", root_path %>
  <% if current_user.shop %>
    <%= link_to "View/Edit Shop", user_shop_path(current_user, current_user.shop) %>
  <% elsif current_user.has_role? :shop_owner %>
  <%= link_to "Create shop", new_user_shop_path(current_user.user_profile.id)  %>
  <% else %>
  <div data-turbolinks="false"><%= link_to "Become a shop owner", user_shop_owners_path(current_user) %></div>
  <% end %>
</div>


<% if User.admin_check(current_user) %>
<div class="all-cards" id="profile-links">
  <%= link_to "Admin Dashboard", users_path %>
</div>
<% end %>

<% if current_user.shop %>
  <div class="all-cards" id="profile-links">
    <%= link_to "Delete your shop", user_shop_path(current_user.id, current_user.shop.id), method: "delete", style: "color:red;"  %>
  </div>
<% end %>


<div class="all-cards" id="profile-links">
  <%= link_to "Delete account", user_registration_path, method: "delete", style: "color:red;" %>
</div>