config/routes.rb
Rails.application.routes.draw do

  get 'users/index'
  get 'users/destroy'
# Home page route for shop index pages
root "shop#index"

#categories index and show pages get routes
get 'categories/index'
get 'categories/:id', to: "categories#show", as: "categories_show"

#  get root set oustide of the resource and before it so that rails finds it first
get "shop/index", to:"shop#index"
get "shop-owners/complete", to:"shop_owners#success"
get "shop-owners/cancel", to: "shop_owners#cancel"

# overiding the devise registration controller path to set my own after registration route
# shop routes nested within user and item routes nested within shop
devise_for :users, controllers: { registrations: "registrations" }
resources :users do
    get "cart", to: "carts#show"
    get "shop-owners", to: "shop_owners#new"
    resources :shop do
      resources :items 
    end
end

delete "users/:user_id/cart/:cart_id/cart_items/:id", to: "cart_items#destroy", as: "user_cart_items"
post "users/:user_id/cart/:cart_id/cart_items", to: "cart_items#create", as: "cart_items"
patch "users/:user_id/cart/:cart_id/cart_items/:id/", to: "cart_items#update", as: "cart_item"

# User profile resource routes
resources :user_profiles

end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy

  def cart_total(user_id)
    @item_total = 0
    @user = User.find(user_id) 
    @user.cart.cart_items.each do |cart_item|
    @item_total += CartItem.item_total((cart_item.quantity).to_d, (cart_item.price).to_d)
    end
    p sprintf('%.2f', @item_total)
   end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  before_action :authorise


  def show
    @user = User.find(params[:user_id])
    @cart_item = CartItem.new
  end

  private

  def authorise

    return if params[:user_id].to_i == current_user.id

    flash[:alert] = "soz...you are only authorised to view your own cart :("
    
    redirect_to user_cart_path(current_user.id)

  end


end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.erb
<div class="all-cards" id="cart-card">
        <h1>Cart</h1>

    <table class="minimalistBlack">
        <thead>
            <td>Item</td>
            <td>Price</td>
            <td>Qty</td>
            <td>Total</td>
            <td>Edit</td>
        </thead>
        <% @user.cart.cart_items.each do |cart_item| %>
            <tbody>
                <tr>
                    <td><%= cart_item.item %></td>
                    <td>$<%= sprintf('%.2f', cart_item.price) %></td>
                    <td>
                            <%= form_with model: @cart_item, method: "patch", url: cart_item_path(current_user.id, current_user.cart.id, cart_item.id), local: true do |f| %>
                            <%= f.number_field(:quantity, in: 1..10, step: 1, value: cart_item.quantity)%> 
                            <%= f.submit "+/-", class: "head-button", style: "font-weight:bolder;" %>
                            <% end %>
                    </td>
                    <td>$<%= p sprintf('%.2f', CartItem.item_total((cart_item.quantity).to_d, (cart_item.price).to_d)) %></td>
                    <td><%= link_to "Del", user_cart_items_path(current_user.id, @user.cart.id, cart_item.id), method: "delete", style: "color:red;" %> </td>
                </tr>
            </tbody>
        <% end %>
        
        <tfoot>
          <tr>
              <td></td>
              <td></td>
              <td></td>
              <td  id="cart-total">Total</td>
              <td  id="cart-total">$<%= @user.cart.cart_total(@user.id)%></td>
              
          </tr>
        </tfoot>
      
    </table>
</div>