config/routes.rb
Rails.application.routes.draw do

  get 'users/index'
  get 'users/destroy'
# Home page route for shop index pages
root "shop#index"

#categories index and show pages get routes
get 'categories/index'
get 'categories/:id', to: "categories#show", as: "categories_show"

#  get root set oustide of the resource and before it so that rails finds it first
get "shop/index", to:"shop#index"
get "shop-owners/complete", to:"shop_owners#success"
get "shop-owners/cancel", to: "shop_owners#cancel"

# overiding the devise registration controller path to set my own after registration route
# shop routes nested within user and item routes nested within shop
devise_for :users, controllers: { registrations: "registrations" }
resources :users do
    get "cart", to: "carts#show"
    get "shop-owners", to: "shop_owners#new"
    resources :shop do
      resources :items 
    end
end

delete "users/:user_id/cart/:cart_id/cart_items/:id", to: "cart_items#destroy", as: "user_cart_items"
post "users/:user_id/cart/:cart_id/cart_items", to: "cart_items#create", as: "cart_items"
patch "users/:user_id/cart/:cart_id/cart_items/:id/", to: "cart_items#update", as: "cart_item"

# User profile resource routes
resources :user_profiles

end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :item_picture
  belongs_to :shop
  has_many :items_category, dependent: :destroy
  has_many :categories, through: :items_category, dependent: :destroy
  accepts_nested_attributes_for :categories, allow_destroy: true
  validates :name, presence: true, length: { in: 3..20 }
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :price, numericality: true, presence: true
  validates :hook, length: { maximum: 45}


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :authenticate_user!, except: [:show]
  before_action :authorise
  skip_before_action :authorise, only: [:show, ]

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
  end

  def new
    @item = Item.new
  end

  def create
    
    @item = current_user.shop.items.create(item_params)
    @item.item_picture.attach(item_params[:item_picture])
    @category = category_check 
  
    if @category.valid? && @item.save(item_params) 
      @item.categories.push(@category)
      redirect_to user_shop_path(current_user.id, current_user.shop.id)
    else
      flash[:alert] = @item.errors.full_messages.to_sentence + @category.errors.full_messages.to_sentence
      redirect_to new_user_shop_item_path(current_user.id, current_user.shop.id, @item.id)
    end



  end

  def edit
    @item = Item.find(params[:id])
  end

  def update

    @item = Item.find(params[:id])
    if item_params[:item_picture]
      @item.item_picture.attach(item_params[:item_picture])
    end
    @category = category_check
    
    if @category.valid? && @item.update(item_params)
      @item.categories.push(@category)
      redirect_to user_shop_item_path(@item)
    else
      flash[:alert] = @item.errors.full_messages.to_sentence + @category.errors.full_messages.to_sentence
      redirect_to edit_user_shop_item_path(@item)
    end

  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to user_shop_path(current_user, current_user.shop.id)
  end

  private 

  def item_params
    params.require(:item).permit(:name, :quantity, :hook, :content, :price, :item_picture)
  end

  def category_params
    params.require(:item).permit(category: [:name])
  end
  # Helper method checks for existing category assigns it to the variable if nill then creates a new category
  def category_check
    
    category = Category.where(name: category_params[:category][:name])

      if ! category[0] 
        category = Category.create(name: category_params[:category][:name])
      end

    return category

  end

  def authorise
  
    return if current_user.id == params[:user_id].to_i && current_user.shop.id == params[:shop_id].to_i 

    flash[:alert] = "soz....You can only create and edit your own shop Items :("
    
    redirect_to user_profile_path(current_user.id)
  
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<div class="all-cards" id="edit_form_card">

    <!-- initialising the rails form helper to render the html form -->
    <%= form_with model: item, method: verb, url: path, local: true do |item_form| %>
           
    <div class="form-field">
        <!-- The name field label and text input field -->
        <%= item_form.label :name, "Item name" %><br>
        <%= item_form.text_field :name, class: "input-field"%>
    </div>
   
    <div class="form-field">
        <!-- The hook field label and text area input -->
        <%= item_form.label :hook, "A quik hook to appeal to sellers!" %><br>
        <%= item_form.text_area :hook, class: "input-field" %>
        </div>
    
    <div class="form-field">
        <!-- The content field label and text area input -->
        <%= item_form.label :content, "Item details" %><br>
        <%= item_form.text_area :content%>
    </div>
   
    <div class="form-field">
       <!-- The content field label and text area input -->
       <%= item_form.label :price, "very nice...how much?" %><br>
       <%= item_form.number_field :price, step: :any, class: "input-field" %>
   </div>
   
    <%= item_form.fields_for :category do |f| %>

    <div class="form-field">
     <%= f.label :name, "Category!" %><br>
     <%= f.text_area :name, class: "input-field" %>
    </div>

    <% end %>

    <div class="form-field">
      <!-- The content field label and text area input -->
      <%= item_form.label :quantity, "Whats your stock quantity?" %><br>
      <%= item_form.number_field :quantity, step: 1, class: "input-field" %>
  </div>
   
   
    <div class="form-field">
      <!-- file attachment field for uploading the shop image. :item_image is
      referenced as attached in the model -->
      <%= item_form.label :item_picture, "Item Image Upload" %><br>
      <%= item_form.file_field :item_picture, id: "file-upload" %>
    </div>
    
    <div class="form-field">
      <!-- The form submit button -->
      <%= item_form.submit "GO!", class: "head-button" %>
    </div>
   
    <% end %>
   
   </div>

app/views/items/_item-card.html.erb
<div class="all-cards" id="item-card">
        <h1><%= item.name %></h1>
    
        <% if item.item_picture.attached? %>
          <%= image_tag (item.item_picture), id: "item-picture" %>
        <% else %>
          <div id="shop-image-placeholder" ><H1>Placeholder</H1></div>
        <% end %>

        <p style="margin-bottom:0;">Price<br>
          $<%= sprintf '%.2f', item.price %></p>
        <p><%= item.hook %></p>

        <% if current_user.shop %>
        <% if current_user.shop.id == item.shop.id %>
        <%= link_to "edit item", edit_user_shop_item_path( item.shop.user, item.shop.id, item.id), style: "color:blue;" "padding-bottom:30px;" %>
        <% end %>  
        <% end %>
        
      
          <%= form_with model: cart_item, local: true, url: cart_items_path(current_user, current_user.cart.id) do |f| %>
            <%= f.hidden_field :item_id, value: item.id %>
            <%= f.number_field(:quantity, in: 1..10, step: 1, value: 1)%>
            <%= f.submit "Cart +", class: "head-button" %> <br> 
          <% end %>
    
    
    </div>

app/views/items/edit.html.erb
<%= render "form", verb: "patch", item: @item, path: user_shop_item_path(current_user, @item.shop.id, @item.id) %>

app/views/items/new.html.erb
<div class="all-cards" id="profile-form-heading-card">
    <h1 id="profile-form-heading">Create your Item</h1>
</div>
<%= render "form", verb: "post", item: @item, path: user_shop_items_path %>

app/views/items/show.html.erb
<%= render "item-card", item: @item, cart_item: @cart_item %>

<div class="all-cards" id="item-content-card">

    <h1 style="margin:0;">Details</h1>

    <p><%= @item.content %></p>

</div>

<% if current_user.id == @item.shop.user.id || User.admin_check(current_user) %>
  <div class="all-cards" id="profile-links">
    <%= link_to "Delete This Item", user_shop_item_path( @item.shop.user.id, @item.shop.id, @item.id), method: "delete", style: "color:red;"  %>
  </div>
<% end %>